# Generated by Django 5.2.8 on 2026-01-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_supplier_alter_product_options_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='Гарантия (мес.)'),
        ),
    ]
