# Generated by Django 5.2.8 on 2026-01-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_warranty_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_info',
            field=models.TextField(blank=True, verbose_name='Контактная информация'),
        ),
    ]
