# Generated by Django 6.0.1 on 2026-01-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_brand_description_supplier_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='Контактная информация'),
        ),
    ]
