# Generated by Django 6.0.1 on 2026-01-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_brand_description_alter_supplier_contact_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(max_length=255, upload_to='products/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
